version: '3.8'

services:
  micamerapro:
    build: .
    image: gutolm/micamerapro:latest
    container_name: micamerapro
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3000
      - DATA_DIR=/app/data
      - ADMIN_PASSWORD=adminpassword # Set your custom administrator console password
      - XIAOMI_USER=             # Optional: pre-populate Xiaomi cloud username on boot
      - XIAOMI_TOKEN=            # Optional: pre-populate Xiaomi cloud password/token on boot
